name: Checkout code
on:  
  workflow_dispatch:                
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run:
          ls .
       

    
